SMLSHARP = smlsharp
SMLFLAGS = -O2
LIBS =
all: main
main: Game.smi main.smi Game.o main.o
	$(SMLSHARP) $(LDFLAGS) -o main main.smi $(LIBS)
Game.o: Game.sml Game.smi
	$(SMLSHARP) $(SMLFLAGS) -o Game.o -c Game.sml
main.o: main.sml Game.smi main.smi
	$(SMLSHARP) $(SMLFLAGS) -o main.o -c main.sml
